// Hardcoded profile for MVP — will be generated by interview TUI later
export const profile = {
  name: "Javier Jiménez de Frutos",
  role: "Technical Lead",
  company: "YouForce by Visma",
  location: "Spain",
  github: "gentlecode1",
  email: "jimenezdefrutos@gmail.com",

  summary: `Technical lead with 8 years of shipping software across the full stack. For the last year, I've been coordinating AI agents to write, review, and deliver production code — designing the harnesses, prompts, and guardrails that make autonomous development reliable. I build the systems that make AI write better code: CI/CD pipelines, testing strategies, agent instruction architectures, and quality gates across multiple stacks (.NET, TypeScript, Angular). I believe autonomous AI development is the future and I'm already building it.`,

  experience: [
    {
      role: "Technical Lead",
      company: "YouForce by Visma",
      period: "January 2025 - Present",
      highlights: [
        "Coordinate AI agents (Claude, Copilot) for autonomous application development — designing agent instructions, prompt architectures, and feedback loops that produce production-ready code",
        "Engineer harnesses and guardrails for AI-driven development: structured agent instruction files, sandbox configurations, and automated quality gates",
        "Define TDD-enforced development patterns with a functional approach — red/green cycles that AI agents follow reliably across the codebase",
        "Drive testing strategy and CI/CD pipeline design: migrated Jasmine/Selenium → Vitest/Playwright; infrastructure with Docker, Kubernetes, Azure Cloud, Terraform",
        "Multi-stack technical leadership: Angular/TypeScript frontend, .NET RESTful APIs, domain design with DDD principles — able to evaluate agent output across all layers",
        "Diagnose and fix agent failures across multiple layers: prompt issues, tool configurations, build pipeline errors, sandbox permissions",
        "Architect the microfrontend system with Stencil web components and Shadow DOM — complex architecture that requires precise agent instructions",
        "System design for massive data processing — microservices, databases, message queues, distributed systems",
        "Built this portfolio as a fully autonomous AI agent system: Cloudflare Worker + Claude streaming + git-blame-based code indexer",
        "Monitoring and alerting with Grafana and Azure Monitor",
      ],
    },
    {
      role: "Angular Front-End Architect & Developer",
      company: "Ilitia Technologies",
      period: "September 2021 - December 2024",
      highlights: [
        "Consultancy delivering Angular/TypeScript applications from scratch for clients across industries — multiple stacks, fast context switching",
        "Progressed from developer to architect, owning technical decisions and CI/CD pipeline design from project inception",
        "Designed application architectures: state management (NgRx), authentication (OAuth 2.0), component structure (standalone)",
        "Built automated build and deployment pipelines; performance optimization: bundle size, load times, caching strategies",
        "Hands-on debugging across the full stack — from TypeScript runtime issues to API integration failures to deployment pipeline errors",
      ],
    },
    {
      role: "Angular Front-End Developer",
      company: "Solutio",
      period: "September 2018 - August 2021",
      highlights: [
        "Developed Angular SPAs with TypeScript across multiple client projects",
        "Authentication flows with MSAL and Microsoft Entra ID",
        "Created and maintained Azure DevOps CI/CD pipelines — first experience designing build and delivery automation",
      ],
    },
  ],

  education: [
    {
      degree: "Bachelor's Degree in Computer Science",
      institution: "University of Burgos (Spain)",
      period: "2015–2018",
      note: "Completed 3 years of 4-year program",
    },
    {
      degree: "Associate Degree in IT Systems Administration",
      institution: "CIFP Juan de Colonia (Spain)",
      period: "2013–2015",
    },
  ],
};
