// Hardcoded profile for MVP — will be generated by interview TUI later
export const profile = {
  name: "Javier Jiménez de Frutos",
  role: "Technical Lead",
  company: "YouForce by Visma",
  location: "Spain",
  github: "gentlecode1",
  email: "jimenezdefrutos@gmail.com",

  summary: `Technical lead with 8 years of shipping software across the full stack. My intent is always to simplify — understanding the base technology and leveraging native platform capabilities over unnecessary abstractions. I think from the product, not just the code — collaborating with UX and business to shape what gets built, not only how. I push to automate everything — from code generation to testing to delivery — using AI agents, CI/CD pipelines, and infrastructure-as-code to ship quality products as efficiently as possible. Building towards fully autonomous orchestrated agent pipelines across multiple stacks (.NET/C#, TypeScript, Angular, Python).`,

  experience: [
    {
      role: "Technical Lead",
      company: "YouForce by Visma",
      period: "January 2025 - Present",
      highlights: [
        "Technical lead of a 6-person team with end-to-end product ownership — collaborate with UX and business stakeholders to identify gaps, propose consistent patterns, and shape product direction",
        "Use Claude as primary development tool — write structured agent instruction files (CLAUDE.md), prompt architectures, and review loops that produce production-ready code",
        "Lead the YouForce CSS design system library (in alpha, adopted as standard for all YouForce teams) — all code generated by Claude through structured agent instructions, demonstrating autonomous AI development at production scale",
        "Design and maintain agent instruction sets that enforce coding standards, architectural patterns, and domain constraints — building towards fully autonomous orchestrated agent pipelines",
        "Architect the microfrontend system with Stencil web components and Shadow DOM — the navigation-bar web component is consumed by every module across the YouForce platform",
        "Led a complete refactor of a legacy Angular application to modern reactive and functional patterns — first with RxJS declarative streams, now migrating to Signals",
        "Drive CI/CD pipeline architecture: GitHub Actions and Azure DevOps workflows, Terraform infrastructure-as-code, automated build → test → deploy pipelines with environment promotion strategies",
        "Multi-stack technical leadership: Angular/TypeScript frontend, .NET (C#) RESTful APIs, domain design with DDD principles — read, evaluate, and debug agent-generated code across all layers",
        "Diagnose and fix agent failures across multiple layers: prompt issues, tool configurations, build pipeline errors, sandbox permissions",
        "System design for massive data processing — microservices, databases, message queues, distributed systems",
        "Operate containerized infrastructure: Docker, Kubernetes on Azure Cloud, monitoring and alerting with Grafana and Azure Monitor",
      ],
    },
    {
      role: "Angular Front-End Architect & Developer",
      company: "Ilitia Technologies",
      period: "September 2021 - December 2024",
      highlights: [
        "Consultancy delivering applications from scratch for clients across industries — progressed from developer to technical lead and architect",
        "Built a KPI dashboard and report wizard frontend from scratch on top of a generic API — Angular with reactive/declarative patterns (RxJS, OnPush)",
        "Developed a Python + Playwright background service that converts web reports to PDF and delivers them via email — solved the challenge of generating chart images for scalable reports (hundreds of pages) by orchestrating batch processing to control memory usage",
        "Developed Python (FastAPI) backend services — REST API design, async endpoints, integration with Angular frontends",
        "Designed application architectures: state management (NgRx), authentication (OAuth 2.0), component structure (standalone)",
        "Built automated CI/CD pipelines; performance optimization: bundle size, load times, caching strategies",
      ],
    },
    {
      role: "Angular Front-End Developer",
      company: "Solutio",
      period: "September 2018 - August 2021",
      highlights: [
        "Developed Angular SPAs with TypeScript across multiple client projects",
        "Authentication flows with MSAL and Microsoft Entra ID",
        "Created and maintained Azure DevOps CI/CD pipelines — first experience designing build and delivery automation",
      ],
    },
  ],

  education: [
    {
      degree: "Bachelor's Degree in Computer Science",
      institution: "University of Burgos (Spain)",
      period: "2015–2018",
      note: "Completed 3 years of 4-year program",
    },
    {
      degree: "Associate Degree in IT Systems Administration",
      institution: "CIFP Juan de Colonia (Spain)",
      period: "2013–2015",
    },
  ],
};
