// Hardcoded profile for MVP — will be generated by interview TUI later
export const profile = {
  name: "Javier Jiménez de Frutos",
  role: "Technical Lead",
  company: "YouForce by Visma",
  location: "Spain",
  github: "gentlecode1",
  email: "jimenezdefrutos@gmail.com",

  summary: `Technical lead with 8 years of shipping software across the full stack. My intent is always to simplify — understanding the base technology and leveraging native platform capabilities over unnecessary abstractions. I think from the product, not just the code — collaborating with UX and business to shape what gets built, not only how. I push to automate everything — from code generation to testing to delivery — using AI agents, CI/CD pipelines, and infrastructure-as-code to ship quality products as efficiently as possible. Building towards fully autonomous orchestrated agent pipelines across multiple stacks (.NET/C#, TypeScript, Angular, Python).`,

  experience: [
    {
      role: "Technical Lead",
      company: "YouForce by Visma",
      period: "January 2025 - Present",
      highlights: [
        "Took ownership of a 6-person team and shaped product direction end-to-end across Angular/TypeScript and .NET (C#) stacks — identified UX gaps, proposed consistent patterns, and aligned technical decisions with business goals",
        "Adopted Claude as primary development tool — wrote structured agent instruction files (CLAUDE.md) and prompt architectures that reliably produce production-ready code",
        "Created the YouForce CSS design system library from scratch — now in alpha and adopted as standard for all YouForce teams, with all code generated by Claude through structured agent instructions",
        "Built and iterated on agent instruction sets that enforce coding standards, architectural patterns, and domain constraints — working towards fully autonomous orchestrated agent pipelines",
        "Architected the microfrontend system with Stencil web components and Shadow DOM — the navigation-bar web component is now consumed by every module across the YouForce platform",
        "Led a complete refactor of a legacy Angular application to modern reactive and functional patterns — first with RxJS declarative streams, now migrating to Signals",
        "Designed the CI/CD pipeline architecture: GitHub Actions and Azure DevOps workflows, Terraform infrastructure-as-code, automated build → test → deploy with environment promotion",
        "Diagnosed and resolved agent failures across prompt issues, tool configurations, build pipeline errors, and sandbox permissions",
        "Contributed to system design for massive data processing — microservices, databases, message queues, distributed systems",
        "Set up and operate containerized infrastructure: Docker, Kubernetes on Azure Cloud, with monitoring and alerting via Grafana and Azure Monitor",
      ],
    },
    {
      role: "Angular Front-End Architect & Developer",
      company: "Ilitia Technologies",
      period: "September 2021 - December 2024",
      highlights: [
        "Progressed from developer to technical lead and architect at a consultancy delivering applications from scratch across industries",
        "Built a KPI dashboard and report wizard frontend from scratch on top of a generic API — Angular with reactive/declarative patterns (RxJS, OnPush)",
        "Developed a Python + Playwright background service that converts web reports to PDF and delivers them via email — solved the challenge of generating chart images for scalable reports (hundreds of pages) by orchestrating batch processing to control memory usage",
        "Developed Python (FastAPI) backend services — REST API design, async endpoints, integration with Angular frontends",
        "Defined application architectures from project inception: state management (NgRx), authentication (OAuth 2.0), standalone component structure",
        "Built automated CI/CD pipelines and optimized application performance: bundle size, load times, caching strategies",
      ],
    },
    {
      role: "Angular Front-End Developer",
      company: "Solutio",
      period: "September 2018 - August 2021",
      highlights: [
        "Developed Angular SPAs with TypeScript across multiple client projects",
        "Authentication flows with MSAL and Microsoft Entra ID",
        "Created and maintained Azure DevOps CI/CD pipelines — first experience designing build and delivery automation",
      ],
    },
  ],

  education: [
    {
      degree: "Bachelor's Degree in Computer Science",
      institution: "University of Burgos (Spain)",
      period: "2015–2018",
      note: "Completed 3 years of 4-year program",
    },
    {
      degree: "Associate Degree in IT Systems Administration",
      institution: "CIFP Juan de Colonia (Spain)",
      period: "2013–2015",
    },
  ],
};
